### ISSUE TITLE
Python 3.12 Error "'DataFrame' object has no attribute 'append'"

### ISSUE THREAD

**Issue by fatalfeel** [tzhangwps/Recession-Predictor#18]
/root/git_source/Recession-Predictor/models/deployment_svm.py
#all_predicted_probs = all_predicted_probs.append(predicted_probs, ignore_index=True)  #error in python 3.12
#need change to
all_predicted_probs = pd.concat([all_predicted_probs, predicted_probs], ignore_index=True)
all_testing_y = all_testing_y._append(self.testing_y)

**Comment by tzhangwps** [comment]
Thanks as always @fatalfeel ! I made the fix on my personal computer, but forgot to update the repo. Fixed here: https://github.com/tzhangwps/Recession-Predictor/pull/19
